In [153]:
import pandas as pd

## Data Load

In [154]:
df = pd.read_csv("gk_qna_dataset.csv")
df

                                              question   answer
0                     What is the capital of "France"?    Paris
1                    What is the capital of "Germany"?   Berlin
2                      What is the capital of "Italy"?     Rome
3                      What is the capital of "Spain"?   Madrid
4                      What is the capital of "Japan"?    Tokyo
..                                                 ...      ...
166          Can you tell me, "Which bird cannot fly"?  Ostrich
167  I was wondering, "What is 'H2O' commonly called"?    Water
168  I was wondering, "Which planet is known as the...     Mars
169  Can you tell me, "What is the main religion in...    Islam
170  Quick question: "Which animal is known for loy...      Dog

[171 rows x 2 columns]

In [155]:
df['question'][0]

'What is the capital of "France"?'

## Data Preprocessing

In [156]:
import re
def tokenization(text):
  text = text.lower()
  #remove quotation
  text = re.sub( r"[\"']","",text)
  #remove space and punctutaion
  text = re.sub(r"[^a-z0-9\s]"," ",text)
  #remove extra spaces
  text = re.sub(r"\s+"," ",text).strip()
  tokens = text.split()
  return tokens

In [157]:
print(tokenization("Don't stop, it's \"great\" "))

['dont', 'stop', 'its', 'great']

In [158]:
#building vocabulary
vocab = {'<UNK>':0}
def build_vocab(row):
  tokenized_question = tokenization(row['question'])
  tokenized_answer = tokenization(row['answer'])
  tokenized_merged = tokenized_question + tokenized_answer

  for token in tokenized_merged:
    if token not in vocab:
      vocab[token]=len(vocab)

In [159]:
df.apply(build_vocab,axis=1)

0      None
1      None
2      None
3      None
4      None
       ...
166    None
167    None
168    None
169    None
170    None
Length: 171, dtype: object

In [160]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq': 68,
 'baghdad': 69,
 'saudi': 70,
 'arabia': 71,
 'riyadh': 72,
 'nigeria': 73,
 'abuja': 74,
 'kenya': 75,
 'nairobi': 76,
 'chile': 77,
 'santiago': 78,
 'who': 79,
 'discovered': 80,
 'gravity': 81,
 'isaac': 82,
 'newton': 83,
 'invented': 84,
 'telephone': 85,
 'alexander': 86,
 'graham': 87,
 'bell': 88,
 'h2o': 89,
 'commonly': 90,
 'called': 91,
 'water': 92,
 'which': 93,
 'gas': 94,
 'do': 95,
 'plants': 96,
 'absorb': 97,
 'carbon': 98,
 'dioxide': 99,
 'planet': 100,
 'known': 101,
 'as': 102,
 'red': 103,
 'mars': 104,
 'painted': 105,
 'mona': 106,
 'lisa': 107,
 'leonardo': 108,
 'da': 109,
 'vinci': 110,
 'largest': 111,
 'ocean': 112,
 'pacific': 113,
 'developed': 114,
 'theory': 115,
 'relativity': 116,
 'albert': 117,
 'einstein': 118,
 'ai': 119,
 'short': 120,
 'for': 121,
 'artificial': 122,
 'intelligence': 123,
 'ml': 124,
 'machine': 125,
 'learning': 126,
 'nlp': 127,
 'natural': 128,
 'language': 129,
 'processing': 130,
 'does': 131,
 'cpu': 132,
 'stand': 133,
 'central': 134,
 'unit': 135,
 'ram': 136,
 'computer': 137,
 'memory': 138,
 'gpu': 139,
 'graphics': 140,
 'a': 141,
 'url': 142,
 'web': 143,
 'address': 144,
 'http': 145,
 'hypertext': 146,
 'transfer': 147,
 'protocol': 148,
 'json': 149,
 'used': 150,
 'data': 151,
 'exchange': 152,
 'sql': 153,
 'database': 154,
 'query': 155,
 'api': 156,
 'mean': 157,
 'application': 158,
 'programming': 159,
 'interface': 160,
 'light': 161,
 'bulb': 162,
 'thomas': 163,
 'edison': 164,
 'airplane': 165,
 'wright': 166,
 'brothers': 167,
 'penicillin': 168,
 'fleming': 169,
 'wrote': 170,
 'hamlet': 171,
 'william': 172,
 'shakespeare': 173,
 'harry': 174,
 'potter': 175,
 'j': 176,
 'k': 177,
 'rowling': 178,
 'country': 179,
 'land': 180,
 'rising': 181,
 'sun': 182,
 'animal': 183,
 'king': 184,
 'jungle': 185,
 'lion': 186,
 'on': 187,
 'earth': 188,
 'blue': 189,
 'whale': 190,
 'bird': 191,
 'cannot': 192,
 'fly': 193,
 'ostrich': 194,
 'loyalty': 195,
 'dog': 196,
 'fruit': 197,
 'typically': 198,
 'apple': 199,
 'yellow': 200,
 'banana': 201,
 'organ': 202,
 'pumps': 203,
 'blood': 204,
 'heart': 205,
 'humans': 206,
 'breathe': 207,
 'oxygen': 208,
 'metal': 209,
 'liquid': 210,
 'at': 211,
 'room': 212,
 'temperature': 213,
 'mercury': 214,
 'instrument': 215,
 'measures': 216,
 'thermometer': 217,
 'pressure': 218,
 'barometer': 219,
 'main': 220,
 'portuguese': 221,
 'spanish': 222,
 'religion': 223,
 'in': 224,
 'islam': 225,
 'national': 226,
 'royal': 227,
 'bengal': 228,
 'tiger': 229,
 'quick': 230,
 'question': 231,
 'you': 232,
 'know': 233,
 'i': 234,
 'was': 235,
 'wondering': 236,
 'hey': 237,
 'about': 238,
 'this': 239,
 'can': 240,
 'tell': 241,
 'me': 242}

In [161]:
#convert text to index
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenization(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text

In [162]:
print(text_to_indices("What is the capital of dhaka",vocab))

[1, 2, 3, 4, 5, 50]

## Dataset and DataLoader

In [163]:
import torch
from torch.utils.data import Dataset,DataLoader

In [164]:
class gkDataset(Dataset):
  def __init__(self,df,vocab):
    super().__init__()
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
    numerical_question = text_to_indices(self.df.iloc[index]['question'],self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'],self.vocab)
    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [165]:
dataset = gkDataset(df,vocab)

In [166]:
dataloader = DataLoader(dataset,batch_size=1,shuffle=True)#batch size 1 don't need padding

In [167]:
for question,answer in dataloader:
  print(question,answer[0])

tensor([[237,   1, 238, 239,  93, 215, 216, 213]]) tensor([217])
tensor([[240, 232, 241, 242,  93, 197,   2, 200]]) tensor([201])
tensor([[240, 232, 241, 242,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[237,   1, 238, 239,   1, 131, 145, 133, 121]]) tensor([146, 147, 148])
tensor([[240, 232, 241, 242,   1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[ 1,  2,  3,  4,  5, 70, 71]]) tensor([72])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[230, 231,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[234, 235, 236,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[ 93, 209,   2, 210, 211, 212, 213]]) tensor([214])
tensor([[230, 231,  93, 202, 203, 204]]) tensor([205])
tensor([[ 79, 114,   3, 115,   5, 116]]) tensor([117, 118])
tensor([[230, 231,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[ 93, 215, 216, 218,  95, 232, 233]]) tensor([219])
tensor([[240, 232, 241, 242,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[ 93, 197,   2, 200]]) tensor([201])
tensor([[ 1,  2,  3,  4,  5, 16]]) tensor([17])
tensor([[ 79,  84,   3, 161, 162,  95, 232, 233]]) tensor([163, 164])
tensor([[ 1,  2,  3,  4,  5, 12]]) tensor([13])
tensor([[ 95, 232, 233,   1,   2,   3, 220, 223, 224,  70,  71]]) tensor([225])
tensor([[  1,   2,   3, 226, 183,   5,  49,  95, 232, 233]]) tensor([227, 228, 229])
tensor([[  1,   2,   3, 220, 129,   5,  18]]) tensor([221])
tensor([[237,   1, 238, 239,  79, 114,   3, 115,   5, 116]]) tensor([117, 118])
tensor([[ 95, 232, 233,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[234, 235, 236,  93, 202, 203, 204]]) tensor([205])
tensor([[ 1,  2,  3,  4,  5, 58]]) tensor([59, 60])
tensor([[ 95, 232, 233,  93, 197,   2, 200]]) tensor([201])
tensor([[ 93, 179,   2, 101, 102,   3, 180,   5, 181, 182,  95, 232, 233]]) tensor([14])
tensor([[ 95, 232, 233,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[ 95, 232, 233,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[ 79, 170, 171]]) tensor([172, 173])
tensor([[ 95, 232, 233,   1, 131, 139, 133, 121]]) tensor([140, 130, 135])
tensor([[ 1,  2,  3,  4,  5, 49]]) tensor([50])
tensor([[234, 235, 236,   1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[ 1,  2,  3,  4,  5, 42, 43]]) tensor([44])
tensor([[234, 235, 236,  93,  94,  95, 206, 207]]) tensor([208])
tensor([[237,   1, 238, 239,   1,   2, 119, 120, 121]]) tensor([122, 123])
tensor([[240, 232, 241, 242,  79, 170, 171]]) tensor([172, 173])
tensor([[240, 232, 241, 242,   1,   2, 119, 120, 121]]) tensor([122, 123])
tensor([[ 93, 191, 192, 193]]) tensor([194])
tensor([[234, 235, 236,  93, 183,   2, 101, 121, 195]]) tensor([196])
tensor([[237,   1, 238, 239,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 93, 100,   2, 101, 102,   3, 103, 100,  95, 232, 233]]) tensor([104])
tensor([[ 79,  84,   3,  85,  95, 232, 233]]) tensor([86, 87, 88])
tensor([[237,   1, 238, 239,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[ 95, 232, 233,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[ 1,  2,  3,  4,  5, 47]]) tensor([48])
tensor([[234, 235, 236,  93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[237,   1, 238, 239,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[  1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[237,   1, 238, 239,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[ 93, 183,   2,  91,   3, 184,   5, 185]]) tensor([186])
tensor([[ 1,  2,  3,  4,  5, 35]]) tensor([36])
tensor([[ 95, 232, 233,   1,   2,   3, 220, 129,   5,  18]]) tensor([221])
tensor([[240, 232, 241, 242,  93,  94,  95, 206, 207]]) tensor([208])
tensor([[ 93, 183,   2, 101, 121, 195]]) tensor([196])
tensor([[240, 232, 241, 242,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[ 93, 215, 216, 213]]) tensor([217])
tensor([[  1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[ 1,  2,  3,  4,  5, 68]]) tensor([69])
tensor([[  1,   2,   3, 220, 129,   5,  12]]) tensor([222])
tensor([[230, 231,  79, 170, 171]]) tensor([172, 173])
tensor([[234, 235, 236,   1,   2, 136]]) tensor([137, 138])
tensor([[234, 235, 236,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[ 1,  2,  3,  4,  5, 27]]) tensor([28])
tensor([[234, 235, 236,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[  1, 131, 156, 157]]) tensor([158, 159, 160])
tensor([[ 79, 105,   3, 106, 107,  95, 232, 233]]) tensor([108, 109, 110])
tensor([[240, 232, 241, 242,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[237,   1, 238, 239,  93, 197,   2, 200]]) tensor([201])
tensor([[ 1,  2,  3,  4,  5, 51]]) tensor([52])
tensor([[234, 235, 236,  79,  84,   3, 165]]) tensor([166, 167])
tensor([[ 93, 215, 216, 218]]) tensor([219])
tensor([[230, 231,  93, 183,   2, 101, 121, 195]]) tensor([196])
tensor([[237,   1, 238, 239,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[ 93, 183,   2,   3, 111, 187, 188,  95, 232, 233]]) tensor([189, 190])
tensor([[230, 231,  93, 183,   2,  91,   3, 184,   5, 185]]) tensor([186])
tensor([[240, 232, 241, 242,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[ 79,  80, 168]]) tensor([ 86, 169])
tensor([[ 1,  2,  3,  4,  5, 20]]) tensor([21])
tensor([[ 95, 232, 233,  79, 170, 171]]) tensor([172, 173])
tensor([[230, 231,  93, 209,   2, 210, 211, 212, 213]]) tensor([214])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
tensor([[ 1,  2,  3,  4,  5, 56]]) tensor([57])
tensor([[230, 231,  79,  84,   3, 161, 162]]) tensor([163, 164])
tensor([[ 79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 1,  2,  3,  4,  5, 39]]) tensor([40, 41])
tensor([[  1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[  1, 131, 145, 133, 121]]) tensor([146, 147, 148])
tensor([[ 93, 197,   2, 198, 103]]) tensor([199])
tensor([[ 1,  2,  3,  4,  5, 61]]) tensor([62])
tensor([[234, 235, 236,   1,   2, 127, 120, 121]]) tensor([128, 129, 130])
tensor([[  1,   2, 136]]) tensor([137, 138])
tensor([[ 93, 202, 203, 204]]) tensor([205])
tensor([[  1,   2,   3, 111, 112,  95, 232, 233]]) tensor([113, 112])
tensor([[240, 232, 241, 242,  79,  80,  81]]) tensor([82, 83])
tensor([[ 1,  2,  3,  4,  5, 18]]) tensor([19])
tensor([[240, 232, 241, 242,   1,   2, 136]]) tensor([137, 138])
tensor([[240, 232, 241, 242,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[ 79,  84,   3, 165]]) tensor([166, 167])
tensor([[234, 235, 236,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[ 1,  2,  3,  4,  5, 22]]) tensor([23, 24])
tensor([[  1,   2, 127, 120, 121]]) tensor([128, 129, 130])
tensor([[ 1,  2,  3,  4,  5, 14]]) tensor([15])
tensor([[ 93, 191, 192, 193,  95, 232, 233]]) tensor([194])
tensor([[ 79, 105,   3, 106, 107]]) tensor([108, 109, 110])
tensor([[230, 231,   1,   2,   3, 220, 129,   5,  18]]) tensor([221])
tensor([[ 95, 232, 233,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[ 95, 232, 233,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([14])
tensor([[237,   1, 238, 239,  79,  80, 168]]) tensor([ 86, 169])
tensor([[ 1,  2,  3,  4,  5, 66]]) tensor([67])
tensor([[237,   1, 238, 239,  93, 183,   2,   3, 111, 187, 188]]) tensor([189, 190])
tensor([[237,   1, 238, 239,  79,  80,  81]]) tensor([82, 83])
tensor([[234, 235, 236,  79, 170, 171]]) tensor([172, 173])
tensor([[230, 231,   1,   2,   3, 111, 112]]) tensor([113, 112])
tensor([[ 1,  2,  3,  4,  5, 33]]) tensor([33, 34])
tensor([[240, 232, 241, 242,   1,   2,   3, 226, 183,   5,  49]]) tensor([227, 228, 229])
tensor([[ 1,  2,  3,  4,  5, 63]]) tensor([64, 65])
tensor([[ 1,  2,  3,  4,  5, 45]]) tensor([46])
tensor([[ 1,  2,  3,  4,  5, 77]]) tensor([78])
tensor([[ 1,  2,  3,  4,  5, 10]]) tensor([11])
tensor([[ 95, 232, 233,  93, 209,   2, 210, 211, 212, 213]]) tensor([214])
tensor([[237,   1, 238, 239,   1,   2, 136]]) tensor([137, 138])
tensor([[234, 235, 236,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[234, 235, 236,   1, 131, 156, 157]]) tensor([158, 159, 160])
tensor([[ 95, 232, 233,  93, 191, 192, 193]]) tensor([194])
tensor([[  1,   2, 119, 120, 121]]) tensor([122, 123])
tensor([[230, 231,   1,   2, 124, 120, 121]]) tensor([125, 126])
tensor([[79, 80, 81]]) tensor([82, 83])
tensor([[ 93,  94,  95, 206, 207]]) tensor([208])
tensor([[237,   1, 238, 239,  93,  94,  95,  96,  97]]) tensor([98, 99])
tensor([[ 1,  2, 89, 90, 91]]) tensor([92])
tensor([[  1,   2,   3, 226, 183,   5,  49]]) tensor([227, 228, 229])
tensor([[  1,   2,   3, 220, 223, 224,  70,  71]]) tensor([225])
tensor([[230, 231,  79,  80, 168]]) tensor([ 86, 169])
tensor([[234, 235, 236,  79,  84,   3,  85]]) tensor([86, 87, 88])
tensor([[  1, 131, 139, 133, 121]]) tensor([140, 130, 135])
tensor([[237,   1, 238, 239,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[237,   1, 238, 239,  93, 215, 216, 218]]) tensor([219])
tensor([[ 1,  2,  3,  4,  5, 29, 30]]) tensor([31, 32])
tensor([[ 93, 183,   2,   3, 111, 187, 188]]) tensor([189, 190])
tensor([[ 1,  2,  3,  4,  5, 25]]) tensor([26])
tensor([[ 1,  2,  3,  4,  5, 53, 54]]) tensor([55])
tensor([[230, 231,  79, 170, 174, 175]]) tensor([176, 177, 178])
tensor([[ 93, 100,   2, 101, 102,   3, 103, 100]]) tensor([104])
tensor([[ 95, 232, 233,   1,   2, 141, 142]]) tensor([143, 144])
tensor([[ 79,  80, 168,  95, 232, 233]]) tensor([ 86, 169])
tensor([[240, 232, 241, 242,  93, 191, 192, 193]]) tensor([194])
tensor([[93, 94, 95, 96, 97]]) tensor([98, 99])
tensor([[  1,   2, 153]]) tensor([154, 155, 129])
tensor([[237,   1, 238, 239,   1, 131, 132, 133, 121]]) tensor([134, 130, 135])
tensor([[  1,   2, 149, 150, 121]]) tensor([151, 152])
tensor([[  1,   2, 141, 142]]) tensor([143, 144])
tensor([[ 1,  2,  3,  4,  5, 37]]) tensor([38])
tensor([[240, 232, 241, 242,  93, 215, 216, 218]]) tensor([219])
tensor([[ 95, 232, 233,  93,  94,  95,  96,  97]]) tensor([98, 99])
tensor([[79, 84,  3, 85]]) tensor([86, 87, 88])
tensor([[ 95, 232, 233,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[237,   1, 238, 239,  79, 105,   3, 106, 107]]) tensor([108, 109, 110])
tensor([[ 1,  2,  3,  4,  5, 75]]) tensor([76])
tensor([[230, 231,  93,  94,  95,  96,  97]]) tensor([98, 99])
tensor([[230, 231,   1, 131, 139, 133, 121]]) tensor([140, 130, 135])
tensor([[234, 235, 236,   1,   2, 149, 150, 121]]) tensor([151, 152])
tensor([[230, 231,  93,  94,  95, 206, 207]]) tensor([208])
tensor([[240, 232, 241, 242,   1,   2,   3, 220, 223, 224,  70,  71]]) tensor([225])
tensor([[234, 235, 236,   1,   2,  89,  90,  91]]) tensor([92])
tensor([[ 93, 202, 203, 204,  95, 232, 233]]) tensor([205])
tensor([[230, 231,   1,   2,   3, 220, 129,   5,  12]]) tensor([222])
tensor([[ 79,  84,   3, 161, 162]]) tensor([163, 164])

## RNN Architechture Implementation

In [168]:
import torch.nn as nn

class simpleRNN(nn.Module):
  def __init__(self,vocab_size,embedding_dim=50,hidden_size=64):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size,embedding_dim)
    self.rnn = nn.RNN(input_size= embedding_dim,hidden_size= hidden_size,batch_first=True)
    self.fc = nn.Linear(hidden_size,vocab_size)

  def forward(self,question):
    embedded = self.embedding(question)
    _,final = self.rnn(embedded)

    return self.fc(final.squeeze(0))

In [169]:
model = simpleRNN(vocab_size=len(vocab))

In [170]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)
epochs = 20

In [171]:
for epoch in range(epochs):
  total_loss = 0
  for question,answer in dataloader:
    optimizer.zero_grad()
    output = model(question)
    target = answer[0][0].unsqueeze(0)
    loss = criterion(output,target)
    loss.backward()
    optimizer.step()
    total_loss += loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 855.283441
Epoch: 2, Loss: 541.002852
Epoch: 3, Loss: 358.212555
Epoch: 4, Loss: 259.063155
Epoch: 5, Loss: 198.025172
Epoch: 6, Loss: 153.355504
Epoch: 7, Loss: 116.314740
Epoch: 8, Loss: 87.447164
Epoch: 9, Loss: 63.325664
Epoch: 10, Loss: 46.980635
Epoch: 11, Loss: 33.942947
Epoch: 12, Loss: 25.125175
Epoch: 13, Loss: 19.228305
Epoch: 14, Loss: 14.981111
Epoch: 15, Loss: 12.048647
Epoch: 16, Loss: 9.792892
Epoch: 17, Loss: 8.148531
Epoch: 18, Loss: 6.863103
Epoch: 19, Loss: 5.865191
Epoch: 20, Loss: 5.038886

In [172]:
def predict(question_text,model,vocab,threshold = 0.5):
  model.eval()
  with torch.no_grad():
    indices = text_to_indices(question_text,vocab)
    x = torch.tensor(indices).unsqueeze(0)

    output = model(x)

    probs = torch.nn.functional.softmax(output,dim=1)

    value,idx = torch.max(probs,dim=1)
    if value.item() <threshold:
      print("I don't know")
      return None

    print(list(vocab.keys())[idx])

In [173]:
predict("What is the capital of Japan ?", model, vocab)

tokyo

In [174]:
# Test
tests = [
    "What is the capital of France?",
    "What is H2O commonly called?",
    "What is red planet?",
    "Which bird cannot fly?",
    "What is the capital of Japan ?",

]
for q in tests:
    print(f"{q:45} → ",end="")
    predict(q, model, vocab)

What is the capital of France?                → paris
What is H2O commonly called?                  → water
What is red planet?                           → mars
Which bird cannot fly?                        → ostrich
What is the capital of Japan ?                → tokyo